version: "3"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: shortify
      POSTGRES_PASSWORD: shortify
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: